name: Replace README

on:
  issue_comment:
    types: [created]

env:
  GITHUB_NAME: yihong0618
  GITHUB_EMAIL: zouzou0208@gmail.com
  COOK_LABEL: Cook

jobs:
  sync:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Configure pip cache
        uses: actions/cache@v1
        id: pip-cache
        with:
          path: venv
          key: pip-1-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
        if: steps.pip-cache.outputs.cache-hit != 'true'

      - name: Replace README
        if: contains(github.event.issue.labels.*.name, ${{ env.COOK_LABEL }}) && github.event.comment.user.login == ${{ github.repository_owner }}
        run: |
          python3 main.py ${{ secrets.G_T }} ${{ github.repository }}
      - name: Push new README
        uses: github-actions-x/commit@v2.6
        with:
          github-token: ${{ secrets.G_T }}
          commit-message: "Replace README"
          files: README.md
          rebase: 'true'
          name: yihong0618 
          email: zouzou0208@gmail.com